load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "two_sum_map_test",
    srcs = ["test.cpp"],
    deps = [
        "//two_sum/src:two_sum_map",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "two_sum_nested_loops_test",
    srcs = ["test.cpp"],
    deps = [
        "//two_sum/src:two_sum_nested_loops",
        "@googletest//:gtest_main",
    ],
)
