load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "two_sum_nested_loops",
    srcs = ["two_sum_nested_loops.cpp"],
    hdrs = ["two_sum.hpp"],
    strip_include_prefix = "",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "two_sum_map",
    srcs = ["two_sum_map.cpp"],
    hdrs = ["two_sum.hpp"],
    strip_include_prefix = "",
    visibility = ["//visibility:public"],
)
