load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "remove_duplicates",
    hdrs = ["remove_duplicates.hpp"],
    srcs = ["remove_duplicates.cpp"],
    visibility = ["//visibility:public"],
    strip_include_prefix = "",
)