load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "two_sum_map_test",
    srcs = ["test.cpp"],
    deps = ["@googletest//:gtest_main", "//TwoSum/src:two_sum_map"],
)

cc_test(
    name = "two_sum_nested_loops_test",
    srcs = ["test.cpp"],
    deps = ["@googletest//:gtest_main", "//TwoSum/src:two_sum_nested_loops"],
)
