load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "valid_parentheses_unordered_map",
    srcs = ["valid_parentheses_unordered_map.cpp"],
    hdrs = ["valid_parentheses.hpp"],
    strip_include_prefix = "",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "valid_parentheses_map",
    srcs = ["valid_parentheses_map.cpp"],
    hdrs = ["valid_parentheses.hpp"],
    strip_include_prefix = "",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "valid_parentheses_slow",
    srcs = ["valid_parentheses_slow.cpp"],
    hdrs = ["valid_parentheses.hpp"],
    strip_include_prefix = "",
    visibility = ["//visibility:public"],
)
