load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "eval_rpn_test",
    srcs = ["test.cpp"],
    deps = [
        "//EvaluateReversePolishNotation/src:eval_rpn",
        "@googletest//:gtest_main",
    ],
)
