load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "eval_rpn",
    hdrs = ["eval_rpn.hpp"],
    srcs = ["eval_rpn.cpp"],
    visibility = ["//visibility:public"],
    strip_include_prefix = "",
)