load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "remove_duplicates_test",
    srcs = ["test.cpp"],
    deps = [
        "//remove_duplicates_from_sorted_array/src:remove_duplicates",
        "@googletest//:gtest_main",
    ],
)
