load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "remove_duplicates_test",
    srcs = ["test.cpp"],
    deps = ["@googletest//:gtest_main", "//RemoveDuplicatesFromSortedArray/src:remove_duplicates"],
)
