load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "set_matrix_zeroes_brute_force",
    srcs = ["set_matrix_zeroes_brute_force.cpp"],
    hdrs = ["set_matrix_zeroes.hpp"],
    strip_include_prefix = "",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "set_matrix_zeroes_optimized",
    srcs = ["set_matrix_zeroes_optimized.cpp"],
    hdrs = ["set_matrix_zeroes.hpp"],
    strip_include_prefix = "",
    visibility = ["//visibility:public"],
)
